/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThumbDataRenderComponent.java
 *
 * Created on 11.11.2011, 23:42:12
 */
package josefx.fdthumbs;

/**
 *
 * @author josefx
 */
class ThumbDataRenderComponent extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /** Creates new form ThumbDataRenderComponent */
    public ThumbDataRenderComponent() {
        initComponents();
    }
    public void setFilePath(String p){
        this.filePath.setText(p);
    }
    public void setThumbPath(String p){
        this.thumbPath.setText(p);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileLab = new javax.swing.JLabel();
        filePath = new javax.swing.JLabel();
        thumbLab = new javax.swing.JLabel();
        thumbPath = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(4, 0));

        fileLab.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        fileLab.setText("File:");
        add(fileLab);

        filePath.setText("PATH_HERE");
        add(filePath);

        thumbLab.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        thumbLab.setText("Thumbnail");
        add(thumbLab);

        thumbPath.setEditable(false);
        thumbPath.setText("PATH_HERE");
        thumbPath.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        thumbPath.setOpaque(false);
        add(thumbPath);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileLab;
    private javax.swing.JLabel filePath;
    private javax.swing.JLabel thumbLab;
    private javax.swing.JTextField thumbPath;
    // End of variables declaration//GEN-END:variables
}
